services:
  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.yaml
    tty: true
    ports:
      - "3333:3333"
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - database-gt
    networks:
      - main

  database-gt:
    image: mysql:8.0
    container_name: database-gt
    command: --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE
    env_file:
      - .env
    restart: always
    entrypoint: ["docker-entrypoint.sh"]
    ports:
      - "3306:3306"
    volumes:
      - mysqldata2:/var/lib/mysql
      - ./database/1.sql:/docker-entrypoint-initdb.d/init.sql

    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - main

  nginx:
    container_name: nginx
    build:
      context: nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - app
    networks:
      - main

networks:
  main:
    driver: bridge

volumes:
  mysqldata2:
    driver: local
